### ISSUE TITLE
Generate Node

### ISSUE THREAD

**Issue by scnncs** [johnroper100/CrowdMaster#25]
I just installed the CrowdMaster Addon but am having trouble with the Generate Node. The 'Generate Agents' button doesn't show.

I am using Blender 2.78 & CrowdMaster 1.2.1

To test if it was a mistake in my node setup, I have downloaded the sample files from the CM website, the 'Generate Agents' button does not show on the Generate Node either however.

Has anyone come across this issue before?

**Comment by johnroper100** [comment]
Which version did you download? The latest release or latest development version?

**Comment by scnncs** [comment]
thanks for the fast response John.
I downloaded the latest release, not the development version

**Comment by Peter-Noble** [comment]
Hey, thanks for the report. I've not come across this issue and I've just tried with Blender 2.78 & CrowdMaster 1.2.1 and it works for me. Would you be able to open the terminal and tell me what it says?

**Comment by scnncs** [comment]
i get this in the 'info'

  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster-master/cm_generation/cm_genNodes.py", line 78, in draw_buttons
    preferences = context.user_preferences.addons["CrowdMaster"].preferences
KeyError: 'bpy_prop_collection[key]: key "CrowdMaster" not found'

**Comment by johnroper100** [comment]
Go to `/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/` and rename `CrowdMAster-master` to `CrowdMaster`

**Comment by scnncs** [comment]
Just did that. Now all nodes read 'Undefined Socket Type'

**Comment by Peter-Noble** [comment]
you may have to reactivate the addon and restart making the node graph.

**Comment by scnncs** [comment]
perfect, that worked! many thanks.

**Comment by scnncs** [comment]
I must oversee something again...
when hitting 'Generate Agents' I received this error:

Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster/cm_generation/__init__.py", line 108, in execute
    genSpaces[tipNode].build(buildRequest)
  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster/cm_generation/cm_templates.py", line 498, in build
    self.inputs["Template"].build(newBuildRequest)
  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster/cm_generation/cm_templates.py", line 378, in build
    self.inputs["Template"].build(buildRequest)
  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster/cm_generation/cm_templates.py", line 261, in build
    topObj = self.inputs["Objects"].build(pos, rot, scale, new_group, defG)
  File "/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons/CrowdMaster/cm_generation/cm_templates.py", line 152, in build
    obj.modifiers[modName].object = dat.objects[aName]
UnboundLocalError: local variable 'aName' referenced before assignment

location: <unknown location>:-1

**Comment by Peter-Noble** [comment]
Please could you screen shot the node set up or send me the blend?

**Comment by scnncs** [comment]
I have reinstalled the addon, renamed the folder & created the node tree anew. Now it works, thank you

**Comment by Peter-Noble** [comment]
Great! Let us know if there is anything else we can help with and we'd also love to hear from you if you create anything cool or if you have any suggestions/requests.
