### ISSUE TITLE
Debug Options -> Run Small Tests produces failure

### ISSUE THREAD

**Issue by fHachenberg** [johnroper100/CrowdMaster#60]
Output is
```

FAILED (errors=1)
Info: Total files 0 | Changed 0 | Failed 0
.Error: You must save your file first!
E..
======================================================================
ERROR: testStartStopSim (CrowdMaster.cm_tests.AddonRegisterTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fabian/.config/blender/2.80/scripts/addons/CrowdMaster/cm_tests.py", line 40, in testStartStopSim
    bpy.ops.scene.cm_start()
  File "/home/fabian/Programme/blender-2.80-4a3348cfe04-linux-glibc219-x86_64/2.80/scripts/modules/bpy/ops.py", line 192, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: You must save your file first!


----------------------------------------------------------------------
Ran 4 tests in 0.067s

FAILED (errors=1)
```

**Comment by johnroper100** [comment]
Crowd Master does not currently work with Blender 2.8. This is something that is being worked on.
